### ISSUE TITLE
ERRO IMPRESSAO EXTRATO VENDA

### ISSUE THREAD

**Issue by PedroCanizela** [OpenAC-Net/OpenAC.Net.Sat#1]
Olá tudo bem?

Estou tentando imprimir o extrato de venda, porém o internal report retorna como 'Referência de objeto não definida para uma instância de um objeto' e não consigo imprimir

**Comment by rftd** [comment]
Se estiver tentando usar o projeto de impressão em Fast OpenSource o mesmo ainda não esta finalizado.

**Comment by PedroCanizela** [comment]
> Se estiver tentando usar o projeto de impressão em Fast OpenSource o mesmo ainda não esta finalizado.

Você teria o projeto de impressão em fast sem ser open source? Não encontrei..

**Comment by rftd** [comment]
Tem 2 projetos de impressão um do Fast Full e outro do Fast Opensource, o do Fast Full funciona normalmente.

**Comment by PedroCanizela** [comment]
Eu achei, porém ele da o erro Conversão especificada não é válida no internalReport.Prepare();
