### ISSUE TITLE
Erro ao enviar pagamento e resposta fiscal

### ISSUE THREAD

**Issue by khaddmussistemas** [OpenAC-Net/OpenAC.Net.Sat#3]
Prezados tudo bem? 

Estou fazendo testes no meu ambiente de desenvolvimento e está me apresentando alguns problema para enviar pagamento e resposta fiscal:
1-Metodo para envia pagamento:

![image](https://user-images.githubusercontent.com/71778467/167489917-80aa65a9-6e94-489e-a2aa-7f3d458680c3.png)

1.1 Retorno

![image](https://user-images.githubusercontent.com/71778467/167489809-b143ab78-3b06-44a1-9668-66ed424a0a46.png)

2.1 Enviando a resposta Fiscal 

![image](https://user-images.githubusercontent.com/71778467/167490737-ad8f1c9c-7677-476c-8bcc-a79fc806276d.png)

2.1 Retorno

![image](https://user-images.githubusercontent.com/71778467/167490804-130b2f3c-9e56-466d-b74b-23bc18fec6ea.png)

Existe alguma coisa que eu possa resolver?

**Comment by rftd** [comment]
Não tem muito que fazer o erro é no integrador fiscal.
