### ISSUE TITLE
Impressão novo layout

### ISSUE THREAD

**Issue by mvtaraujo** [OpenAC-Net/OpenAC.Net.Sat#7]
Olá pessoal!

Desculpem se já existe resposta pra isso e não encontrei.

Sempre utilizei o componente Acbr para impressao do Extrato CF-e SAT com FastReports e nunca tive problemas.

Comecei a ter uns problemas de versão em alguns clientes e precisei dar uma atenção maior nisso. Acontece que vi no manual de orientacao que a partir de 01/01/2019 é obrigatorio o novo layout que imprime o QRcode do lado esquerdo e as informações do consumidor, numero de serie do lado direito.

Sabem me informar se é obrigatório mesmo? Ou se ficou facultativo? Pois pelo que vi, no OpenAC.Net.Sat ainda utiliza o layout antigo, um abaixo do outro.

**Comment by rftd** [comment]
O layout com o QrCode Lateral é opcional, e eu não implementei o mesmo.

**Comment by mvtaraujo** [comment]
Obrigado pela resposta @rftd, isso que eu queria saber e não tinha encontrado resposta. No manual que estou vendo está como obrigatório.

![image](https://user-images.githubusercontent.com/2230616/204615689-f26d6391-1301-438f-a619-6e533dd9c793.png)

**Comment by rftd** [comment]
Este manual que peguei é o último disponível para download na SEFAZ de SP.

Manual de Orientação do SAT – versão 02.18.02 – 02 de maio de 2019

**Comment by mvtaraujo** [comment]
Perfeito. Obrigado!
