### ISSUE TITLE
Erro ao Executar o Projeto

### ISSUE THREAD

**Issue by EdsonRodrigoBA** [OpenAC-Net/OpenAC.Net.Sat#8]
Ao tentar executar o projeto, com a biblioteca na pasta C:/sat/SAT.dll.
![image](https://github.com/OpenAC-Net/OpenAC.Net.Sat/assets/16749983/de407c85-2233-4f45-a3fc-8d6af513f823)

Sabem me informar o que pode ser?

**Comment by rftd** [comment]
Provavelmente esta carregando uma dll x64 em um programa x86 ou vice-versa
