### ISSUE TITLE
Estou com este problema, alguém já passou por isso?

### ISSUE THREAD

**Issue by WPita** [OpenAC-Net/OpenAC.Net.Sat#9]
Managed Debugging Assistant 'PInvokeStackImbalance' : 'Uma chamada para a função PInvoke 'OpenAC.Net.Sat!OpenAC.Net.Sat.Library.SatCdecl+Delegates+EnviarDadosVenda::Invoke' desbalanceou a pilha. Isso ocorreu provavelmente porque a assinatura gerenciada de PInvoke não corresponde à assinatura de destino não gerenciada. Verifique se a convenção e o parâmetro de chamada da assinatura de PInvoke são iguais aos da assinatura não gerenciada de destino.'

**Comment by rftd** [comment]
Erro muito comum, você informou o tipo errado de Calling Convention, se estiver usando Cdecl mude para stdcal ou vice-versa.

**Comment by WPita** [comment]
Exatamente isso, fiz a correção e funcionou
